version: "3"

volumes:
  db:

services:
  bot:
    build: .
    restart: always
    volumes:
      - ./data:/data:rw
    environment:
      - BOT_TOKEN=
      - ADMIN_CHAT=
      - DEBUG=1
    logging:
      options:
        max-size:
          "10m"
        max-file:
          "3"